site_name: My Knowledge Base
repo_url: https://github.com/autumnkids/miscellaneous-study-notes
repo_name: autumnkids/miscellaneous-study-notes
nav:
  - Home: index.md
  - Database:
    - Database Internal: database/database-internal.md
    - PostgreSQL: database/postgresql.md
    - MongoDB: database/mongodb.md
    - Performance Tips: database/performance-tips.md
  - DSA:
    - B Tree: dsa/b-tree.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
